definitions:
    dotmailer_email_campaign_creation:
        label:   'Create Email Campaign for Dotmailer Campaign'
        enabled: true
        order:   10
        entity:  OroCRM\Bundle\DotmailerBundle\Entity\Campaign
        exclude_definitions: [dotmailer_email_campaign_creation]
        actions_configuration:
            - '@assign_value':
                attribute: $.addressBook
                value: null
            - '@call_method':
                conditions:
                    '@not_empty': $addressBooks
                parameters:
                    attribute: $.addressBook
                    method: first
                    object: $addressBooks
            # Prepare constants values
            - '@assign_constant_value':
                attribute: $.statusSent
                value: OroCRM\Bundle\DotmailerBundle\Entity\Campaign::STATUS_SENT
            - '@assign_constant_value':
                attribute: $.scheduleManual
                value: OroCRM\Bundle\CampaignBundle\Entity\EmailCampaign::SCHEDULE_MANUAL
            - '@assign_constant_value':
                attribute: $.dotmailerTransport
                value: OroCRM\Bundle\DotmailerBundle\Transport\DotmailerEmailCampaignTransport::NAME
            # Create OroCRM EmailCampaign
            - '@tree':
                # If OroCRM EmailCampaign not exists and
                # Dotmailer Campaign relates to OroCRM MarketingList and
                # Dotmailer Campaign has "sent" status
                conditions:
                    '@and':
                        - '@empty': $emailCampaign
                        - '@not_empty': $.addressBook
                        - '@not_empty': $.addressBook.marketingList
                        - '@equal': [$status, $.statusSent]
                actions:
                    - '@create_entity': # Create OroCRM EmailCampaign
                        class:     OroCRM\Bundle\CampaignBundle\Entity\EmailCampaign
                        attribute: $emailCampaign
                        data:
                            name: $name
                            description: $subject
                            schedule: $.scheduleManual
                            sent: true
#                                    sentAt: $sendTime
                            senderEmail: $fromAddress
                            senderName: $fromName
                            transport: $.dotmailerTransport
                            owner: $channel.defaultUserOwner
                            organization: $channel.defaultUserOwner.organization
                            marketingLIst: $.addressBook.marketingList
                    - '@create_entity': # Create DotmailerTransportSettings
                        class:     OroCRM\Bundle\DotmailerBundle\Entity\DotmailerTransportSettings
                        attribute: $emailCampaign.transportSettings
                        data:
                            channel: $channel

    dotmailer_contact_activity_update:
        label:   'Synchronizes OroCRM Marketing List Item with Dotmailer Contact Activity'
        enabled: true
        order:   20
        entity:  OroCRM\Bundle\DotmailerBundle\Entity\Activity
        exclude_definitions: [dotmailer_contact_activity_update]
        actions_configuration:
            - '@update_email_campaign_dm_statistics': ~

    dotmailer_handle_contact_state:
        label:   Check MarketingListItem State for Dotmailer Contact
        enabled: true
        entity:  OroCRM\Bundle\DotmailerBundle\Entity\AddressBookContact
        exclude_definitions: [dotmailer_handle_contact_state]
        actions_configuration:
            # Prepare constants values
            - '@assign_constant_value':
                attribute: $.statusSubscribed
                value: OroCRM\Bundle\DotmailerBundle\Entity\Contact::STATUS_SUBSCRIBED
            - '@assign_constant_value':
                attribute: $.statusSoftBounced
                value: OroCRM\Bundle\DotmailerBundle\Entity\Contact::STATUS_SOFTBOUNCED
            - '@tree':
                conditions:
                    '@or':
                        - '@equal': [$status, $.statusSubscribed]
                        - '@equal': [$status, $.statusSoftBounced]
                actions:
                    - '@remove_marketing_list_unsubscribed_item': ~
                    - '@remove_marketing_list_removed_item': ~
            # Create OroCRM MarketingListUnsubscribedItem
            - '@dm_create_marketing_list_unsubscribed_item':
                conditions:
                    '@and':
                        - '@not_equal': [$status, $.statusSubscribed]
                        - '@not_equal': [$status, $.statusSoftBounced]

    schedule_dotmailer_address_book_synchronization:
        label:   Schedule Dotmailer Address Book synchronization
        enabled: true
        entity:  OroCRM\Bundle\DotmailerBundle\Entity\AddressBook
        actions_configuration:
            - '@tree':
                conditions:
                    '@and':
                        - '@not_empty': $marketingList
                        - '@not_empty': $channel
                actions:
                    - '@format_string':
                        attribute: $.addressBook
                        string: 'address-book=%adddress_book_id%'
                        arguments:
                            adddress_book_id: $id
                    - '@format_string':
                        attribute: $.integration
                        string: '--integration-id=%integration_id%'
                        arguments:
                            integration_id: $channel.id
                    - '@create_entity':
                        class: JMS\JobQueueBundle\Entity\Job
                        attribute: $.syncJob
                        flush: true
                        arguments:
                            - 'oro:cron:integration:sync'
                            - [$.addressBook, $.integration, '-v']

    dotmailer_handle_removed_address_book_contact:
        label:   Update MarketingListItem State in case of Dotmailer contact export was rejected
        enabled: true
        entity:  OroCRM\Bundle\DotmailerBundle\Entity\AddressBookContact
        actions_configuration:
            - '@dm_create_marketing_list_removed_item': ~

triggers:
    dotmailer_email_campaign_creation:
        -
            event:    create
            queued:   false

    dotmailer_contact_activity_update:
        -
            event:    create
            queued:   false
        -
            event:    update
            queued:   false

    dotmailer_handle_contact_state:
        -
            event:    create
            queued:   false
        -
            event:    update
            queued:   false

    dotmailer_handle_removed_address_book_contact:
        -
            event:    delete
            queued:   false


    schedule_dotmailer_address_book_synchronization:
        -
            event:    update
            field:    marketingList
