config:
    paths:
        'orodotmailer/js/sync-buttons-handler': 'bundles/orodotmailer/js/sync-buttons-handler.js'
        'orodotmailer/js/integration-connection': 'bundles/orodotmailer/js/integration-connection.js'
        'orodotmailer/js/app/components/dm-resource-component': 'bundles/orodotmailer/js/app/components/dm-resource-component.js'
        'orodotmailer/js/app/views/field-choice-item-view': 'bundles/orodotmailer/js/app/views/field-choice-item-view.js'
        'oro/select2-autocomplete-channel-aware-address-book-component': 'bundles/orodotmailer/js/app/components/select2-autocomplete-channel-aware-address-book-component.js'
        'orodotmailer/js/app/components/mapping-component': 'bundles/orodotmailer/js/app/components/mapping-component.js'
        'orodotmailer/js/app/models/mapping-model': 'bundles/orodotmailer/js/app/models/mapping-model.js'
        'orodotmailer/js/datafield-view': 'bundles/orodotmailer/js/datafield-view.js'
